config/routes.rb
Nith::Application.routes.draw do
  
  resources :categories

  resources :goals do
    resources :log_items
  end

  devise_for :users
  devise_scope :user do
    match 'login' => 'devise/sessions#new'
    match 'logout' => 'devise/sessions#destroy'
    match 'register' => 'devise/registrations#new'
  end
  
  root :to => 'goals#index'
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :goals
  
  def to_s
    name
  end
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :log_items
  
  scope :completed, where(:completed => true)
end

app/models/log_item.rb
class LogItem < ActiveRecord::Base
  belongs_to :goal
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :goals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_objects
  
  # GET /
  # GET /goals
  # GET /goals.json
  def index
    @goals = current_user.goals

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @goals }
    end
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @goal }
    end
  end

  # GET /goals/new
  # GET /goals/new.json
  def new
    @goal = current_user.goals.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @goal }
    end
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = current_user.goals.build(params[:goal])

    respond_to do |format|
      if @goal.save
        format.html { redirect_to goals_path, notice: 'Goal was successfully created.' }
        format.json { render json: @goal, status: :created, location: @goal }
      else
        format.html { render action: "new" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /goals/1
  # PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update_attributes(params[:goal])
        format.html { redirect_to goals_path, notice: 'Goal was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to goals_url }
      format.json { head :ok }
    end
  end
  
  def load_objects
    @goal = current_user.goals.find params[:id] if params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/log_items_controller.rb
class LogItemsController < ApplicationController
  
  before_filter :load_objects
  
  # GET /log_items
  # GET /log_items.json
  def index
    @log_items = @goal.log_items

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @log_items }
    end
  end

  # GET /log_items/1
  # GET /log_items/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @log_item }
    end
  end

  # GET /log_items/new
  # GET /log_items/new.json
  def new
    @log_item = @goal.log_items.build
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @log_item }
    end
  end

  # GET /log_items/1/edit
  def edit
  end

  # POST /log_items
  # POST /log_items.json
  def create
    @log_item = @goal.log_items.build(params[:log_item])

    respond_to do |format|
      if @log_item.save
        format.html { redirect_to goal_log_items_path, notice: 'Log item was successfully created.' }
        format.json { render json: @log_item, status: :created, location: @log_item }
      else
        format.html { render action: "new" }
        format.json { render json: @log_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /log_items/1
  # PUT /log_items/1.json
  def update
    respond_to do |format|
      if @log_item.update_attributes(params[:log_item])
        format.html { redirect_to goal_log_items_path, notice: 'Log item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @log_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /log_items/1
  # DELETE /log_items/1.json
  def destroy
    @log_item.destroy

    respond_to do |format|
      format.html { redirect_to goal_log_items_url }
      format.json { head :ok }
    end
  end
  
  def load_objects
    @goal = Goal.find(params[:goal_id]) if params[:goal_id]
    @log_item = @goal.log_items.find(params[:id]) if params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/log_items_helper.rb
module LogItemsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<h1>Listing goals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Completed</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @goals.each do |goal| %>
  <tr>
    <td><%= goal.name %></td>
    <td><%= goal.category %></td>
    <td><%= goal.completed? ? 'Ja' : 'Nei' %></td>
    <td><%= goal.log_items.sum(:score) %></td>
    <td><%= link_to 'Show', goal %></td>
    <td><%= link_to 'Log progress', new_goal_log_item_path(goal) %></td>
    <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
    <td><%= link_to 'Destroy', goal, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<h1>New goal</h1>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @goal.name %>
</p>

<p>
  <b>Category:</b>
  <%= @goal.category %>
</p>

<p>
  <b>Completed:</b>
  <%= @goal.completed %>
</p>

<p>
  <%- @goal.log_items.each do |item| -%>
    <%= item.comment %>: <%= item.score %><br />
  <%- end -%>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>

app/views/home/index.html.erb
<h1>Welcome</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nith</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <header>
      <nav class="round">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <%- if user_signed_in? -%>
            <li><%= link_to "Goals", goals_path %></li>
            <li><%= link_to "Categories", categories_path %></li>
            <li><%= link_to "Logout", logout_path %></li>
          <% else %>
            <li><%= link_to "Login", login_path %> or <%= link_to "Register", register_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>

    <section class="round">
      <%- if notice -%>
        <p class="notice"><%= notice %></p>
      <%- end -%>
      <%- if alert -%>
        <p class="alert"><%= alert %></p>
      <%- end -%>
      <%= yield %>
    </section>

  </div>
</body>
</html>

app/views/log_items/_form.html.erb
<%= form_for([:goal, @log_item]) do |f| %>
  <% if @log_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log_item.errors.count, "error") %> prohibited this log_item from being saved:</h2>

      <ul>
      <% @log_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/log_items/edit.html.erb
<h1>Edit log for <%= @goal.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', [@goal, @log_item] %> |
<%= link_to 'Back', goal_log_items_path %>

app/views/log_items/index.html.erb
<h1>Listing log items</h1>

<table>
  <tr>
    <th>Goal</th>
    <th>Comment</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @log_items.each do |log_item| %>
  <tr>
    <td><%= log_item.goal.name %></td>
    <td><%= log_item.comment %></td>
    <td><%= log_item.score %></td>
    <td><%= link_to 'Show', [@goal, log_item] %></td>
    <td><%= link_to 'Edit', edit_goal_log_item_path(@goal, log_item) %></td>
    <td><%= link_to 'Destroy', [@goal, log_item], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%# link_to 'New Log item', new_log_item_path %>

app/views/log_items/new.html.erb
<h1>New log for <%= @goal.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', goal_log_items_path %>

app/views/log_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Goal:</b>
  <%= @log_item.goal.name %>
</p>

<p>
  <b>Comment:</b>
  <%= @log_item.comment %>
</p>

<p>
  <b>Score:</b>
  <%= @log_item.score %>
</p>


<%= link_to 'Edit', edit_goal_log_item_path(@goal, @log_item) %> |
<%= link_to 'Back', goal_log_items_path %>